---
- name: "Get existing spritesheet modified stats ({{ item }})"
  ansible.builtin.stat:
    path: "{{ tilesets_dir }}/{{ item }}.png"
  register: output_stats

- name: "Get current source modified stats ({{ item }})"
  ansible.builtin.stat:
    path: "{{ asset_sources_dir }}/{{ item }}.aseprite"
  register: input_stats

- name: "Regenerate Aseprite sprite-sheet ({{ item }})"
  when: false
  # https://www.aseprite.org/docs/cli/
  ansible.builtin.shell:
    cmd: |
      {{ bin_dir }}/aseprite \
      --batch \
      --sheet-columns 8 \
      --merge-duplicates \
      --ignore-empty \
      --list-tags \
      --list-slices \
      --export-tileset \
      --filename-format frame_{frame} \
      --format json-hash \
      --data {{ tilesets_dir }}/{{ item }}-tileset.json \
      {{ asset_sources_dir }}/{{ item }}.aseprite \
      --sheet {{ tilesets_dir }}/{{ item }}-tileset.png
  changed_when: true

- name: "Regenerate Aseprite sprite-sheet ({{ item }})"
  when: not output_stats.stat.exists or input_stats.stat.mtime > output_stats.stat.mtime
  # https://www.aseprite.org/docs/cli/
  ansible.builtin.shell:
    cmd: |
      {{ bin_dir }}/aseprite \
      --batch \
      --trim \
      --sheet-columns 8 \
      --trim-by-grid \
      --merge-duplicates \
      --list-tags \
      --list-slices \
      --filename-format frame_{frame} \
      --format json-hash \
      --data {{ tilesets_dir }}/{{ item }}.json \
      {{ asset_sources_dir }}/{{ item }}.aseprite \
      --sheet {{ tilesets_dir }}/{{ item }}.png
  changed_when: true
