# ansible-playbook build_spritesheets.yaml
---
- name: "Setup dev host"
  hosts: localhost
  gather_facts: false
  vars:
    bin_dir: "{{ playbook_dir | dirname }}/bin"
    asset_sources_dir: "{{ playbook_dir | dirname }}/asset_sources"
    tilesets_dir: "{{ playbook_dir | dirname }}/enigmagen/tilesets"

  tasks:
    - name: "Process PXOs"
      include_tasks: tasks/export_pixelorama_spritesheet.yaml
      loop:
        - "mars/mars_surface"

    - name: "Process Aesprites"
      include_tasks: tasks/export_aseprite_spritesheet.yaml
      loop:
        - "mars/astronaut"
        - "mars/small_rover"
