# ansible-playbook build_spritesheets.yaml
---
- name: Setup dev host
  hosts: localhost
  vars:
    bin_dir: "{{ playbook_dir | dirname }}/bin"
    asset_sources_dir: "{{ playbook_dir | dirname }}/asset_sources"
    tilesets_dir: "{{ playbook_dir | dirname }}/enigmagen/tilesets"

  # pre_tasks:
  #   - name: Create local bin folder
  #     ansible.builtin.file:
  #       path: "/home/{{ ansible_user_id }}/.local/bin"
  #       mode: '0775'
  #       state: directory

  #   - name: Create dev bin folder
  #     ansible.builtin.file:
  #       path: "{{ bin_dir }}"
  #       mode: '0775'
  #       state: directory

  tasks:
    - name: "Generate sprite-sheet"
      ansible.builtin.command:
        argv:
          - "{{ bin_dir }}/pixelorama"
          - "--headless"
          - "--quit"
          - "--spritesheet"
          - "--output"
          - "{{ tilesets_dir }}/mars_surface.png"
          - "{{ asset_sources_dir }}/mars/mars_surface.pxo"



# /home/mark/dev/Enigmagen/bin/pixelorama --headless --quit --spritesheet --output /home/mark/dev/Enigmagen/enigmagen/tilesets/mars_surface.png /home/mark/dev/Enigmagen/asset_sources/mars/mars_surface.pxo
